src/Entity/Invoice/Invoice.php
<?php

namespace App\Entity\Invoice;

use App\Entity\Company\Company;
use App\Entity\Invoice\Item;
use App\Entity\Payment\Payment;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Invoice\InvoiceRepository")
 * @UniqueEntity(
 *     fields={"number", "issuer"},
 *     message="Já existe uma fatura com este número de sequência emitida por esta empresa.",
 *     errorPath="number",
 * )
 */
class Invoice {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     * @Assert\NotNull()
     * @Assert\NotBlank(message="O número de fatura é obrigatório.")
     * @Assert\Length(min="1", max="16")
     */
    private $number;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotNull(message="O campo data é obrigatório.")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company\Company", inversedBy="issuedInvoices")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotIdenticalTo(propertyPath="client", message="O cliente e o emissor não podem ser a mesma empresa.")
     */
    private $issuer;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company\Company", inversedBy="receivedInvoices")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotIdenticalTo(propertyPath="issuer", message="O cliente e o emissor não podem ser a mesma empresa.")
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Invoice\Item", mappedBy="invoice", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({"quantity" = "asc"})
     * @Assert\Valid()
     */
    private $items;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Payment\Payment", mappedBy="invoice", orphanRemoval=true, cascade={"persist", "remove"})
     * @Assert\Valid()
     */
    private $payments;

    public function __construct() {
        $this->items = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getNumber(): ?string {
        return $this->number;
    }

    public function setNumber(string $number): self {
        $this->number = $number;

        return $this;
    }

    public function getDate(): ?\DateTime {
        return $this->date;
    }

    public function setDate(\DateTime $date): self {
        $this->date = $date;

        return $this;
    }

    public function getIssuer(): ?Company {
        return $this->issuer;
    }

    public function setIssuer(?Company $company): self {
        $this->issuer = $company;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection {
        return $this->items;
    }

    public function addItem(Item $item): self {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setInvoice($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getInvoice() === $this) {
                $item->setInvoice(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setInvoice($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self {
        if ($this->payments->contains($payment)) {
            $this->payments->removeElement($payment);
            // set the owning side to null (unless already changed)
            if ($payment->getInvoice() === $this) {
                $payment->setInvoice(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Company {
        return $this->client;
    }

    public function setClient(?Company $client): self {
        $this->client = $client;

        return $this;
    }

    public function getSubTotal() : float {
        $items = $this->getItems();
        $total = 0;
        foreach($items as $item){
            $total += $item->getSubTotal();
        }

        return $total;
    }

    public function getTotal(): float {
        $items = $this->getItems();
        $total = 0;
        foreach($items as $item){
            $total += $item->getTotal();
        }

        return $total;
    }

    public function getTotalPaid(): float {
        $total = 0;
        foreach ($this->getPayments() as $payment) {
            $total += $payment->getAmount();
        }
        return $total;
    }

    public function getUnpaidAmount(): float {
        return $this->getTotal() - $this->getTotalPaid();
    }

    public function isPaid() : bool {
        return $this->getTotalPaid() >= $this->getTotal();
    }

    public function getMissingToPay(){
        $missing = $this->getTotal()-$this->getTotalPaid();
        return max($missing, 0);
    }

    public function getTotalQuantity() : float {
        $items = $this->getItems();
        $total = 0;
        foreach($items as $item){
            $total += $item->getQuantity();
        }

        return $total;
    }

    public function getTotalWaste() : float {
        $items = $this->getItems();
        $total = 0;
        foreach($items as $item){
            $total += $item->getWaste();
        }

        return $total;
    }
}

src/Form/Invoice/InvoiceType.php
<?php

namespace App\Form\Invoice;

use App\Entity\Company\Company;
use App\Entity\Invoice\Invoice;
use App\Entity\Invoice\Item;
use App\Entity\Payment\Payment;
use App\Form\Payment\PaymentType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('number', TextType::class, [
                'label' => 'Número da fatura',
            ])
            ->add('date', DateType::class, [
                'label' => 'Data',
                'widget' => 'single_text',
            ])
            ->add('issuer', EntityType::class, [
                'class' => Company::class,
                'label' => 'Emissor',
                'choice_label' => 'name',
            ])
            ->add('client', EntityType::class, [
                'class' => Company::class,
                'label' => 'Cliente',
                'choice_label' => 'name',
            ])
            ->add('items', CollectionType::class, [
                'label' => 'Items',
                'entry_type' => ItemType::class,
                'entry_options' => [
                    'label' => false
                ],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'delete_empty' => true,
            ])
            ->add('payments', CollectionType::class, [
                'label' => 'Pagamentos',
                'entry_type' => PaymentType::class,
                'entry_options' => [
                    'label' => false
                ],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'delete_empty' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Form/Invoice/ItemType.php
<?php

namespace App\Form\Invoice;

use App\Entity\Invoice\Item;
use App\Entity\Product\Product;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity', NumberType::class, [
                'label' => 'Quantidade',
            ])
            ->add('pricePerUnit', NumberType::class, [
                'label' => 'Preço por unidade',
            ])
            ->add('waste', NumberType::class, [
                'label' => 'Refúgo',
            ])
            ->add('product', EntityType::class, [
                'label' => 'Produto',
                'class' => Product::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Item::class,
        ]);
    }
}

src/Controller/Backend/Invoice/InvoiceController.php
<?php

namespace App\Controller\Backend\Invoice;

use App\Controller\Backend\BaseController;
use App\Entity\Invoice\Invoice;
use App\Form\Invoice\InvoiceType;
use App\Repository\Company\CompanyRepository;
use App\Repository\Invoice\InvoiceRepository;
use App\Repository\Product\ProductRepository;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backend/invoice")
 */
class InvoiceController extends BaseController {
    /**
     * @Route("/", name="backend_invoice_invoice_index", methods={"GET"})
     */
    public function index(InvoiceRepository $invoiceRepository, ProductRepository $productRepository, CompanyRepository $companyRepository, Request $request): Response {
        $invoices = $this->paginateWithSorting($invoiceRepository, $request);
        /** @var $invoices Invoice[]|PaginatorInterface */


        return $this->render('backend/invoice/invoice/index.html.twig', [
            'invoices' => $invoices,
            'products' => $productRepository->findAll(),
            'companies' => $companyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="backend_invoice_invoice_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response {
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('backend_invoice_invoice_index');
        }

        return $this->render('backend/invoice/invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/show", name="backend_invoice_invoice_show", methods={"GET"})
     */
    public function show(Request $request, Invoice $invoice): Response {
        return $this->render('backend/invoice/invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }


    /**
     * @Route("/{id}/edit", name="backend_invoice_invoice_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Invoice $invoice): Response {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('backend_invoice_invoice_index', [
                'id' => $invoice->getId(),
            ]);
        }

        return $this->render('backend/invoice/invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_invoice_invoice_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Invoice $invoice): Response {
        if ($this->isCsrfTokenValid('delete' . $invoice->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_invoice_invoice_index');
    }
}

src/Controller/Backend/Invoice/ItemController.php
<?php

namespace App\Controller\Backend\Invoice;

use App\Controller\Backend\BaseController;
use App\Entity\Invoice\Item;
use App\Repository\Company\CompanyRepository;
use App\Repository\Invoice\ItemRepository;
use App\Repository\Product\ProductRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backend/invoice/item")
 */
class ItemController extends BaseController {
    /**
     * @Route("/", name="backend_invoice_item_index", methods={"GET"})
     */
    public function index(ItemRepository $itemRepository, ProductRepository $productRepository, CompanyRepository $companyRepository, Request $request): Response {
        $items = $this->paginateWithSorting($itemRepository, $request);
        /** @var $items Item[]|PaginatorInterface */


        return $this->render('backend/invoice/item/index.html.twig', [
            'items' => $items,
            'products' => $productRepository->findAll(),
            'companies' => $companyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_invoice_item_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Item $item): Response {
        if ($this->isCsrfTokenValid('delete' . $item->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($item);
            $item->getInvoice()->removeItem($item);

            if($item->getInvoice()->getItems()->isEmpty() && $item->getInvoice()->getPayments()->isEmpty()){
                $entityManager->remove($item->getInvoice());
            }
            $entityManager->flush();

        }

        return $this->redirectToRoute('backend_invoice_invoice_index');
    }
}

templates/backend/invoice/invoice/_delete_form.html.twig
<form method="post" class="d-inline" action="{{ path('backend_invoice_invoice_delete', {'id': invoice.id}) }}"
      onsubmit="return confirm('Tem a certeza que pretende eliminar este item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn btn-danger btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-trash"></i>
        </span>
    </button>
</form>

templates/backend/invoice/invoice/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_row(form.number) }}
    {{ form_row(form.date) }}
    {{ form_row(form.issuer) }}
    {{ form_row(form.client) }}


    {{ form_row(form.items) }}

    <button type="button"
            class="btn btn-danger remove-collection-element-form"
            data-list-selector="#invoice_items"><i class="fa fa-times"></i> Remover item
    </button>

    <button type="button"
            class="btn btn-success add-collection-element-form"
            data-list-selector="#invoice_items"><i class="fa fa-plus"></i> Adicionar item
    </button>

    <hr />

    {{ form_row(form.payments) }}

    <button type="button"
            class="btn btn-danger remove-collection-element-form"
            data-list-selector="#invoice_payments"><i class="fa fa-times"></i> Remover Pagamento
    </button>

    <button type="button"
            class="btn btn-success add-collection-element-form"
            data-list-selector="#invoice_payments"><i class="fa fa-plus"></i> Adicionar Pagamento
    </button>

    <hr />

    {{ form_widget(form) }}



    <hr />

    <button class="btn btn-success btn-icon-split">
        <span class="icon text-white-50">
          <i class="fas fa-check"></i>
        </span>
        <span class="text">{{ button_label|default('Guardar') }}</span>
    </button>

{{ form_end(form) }}

templates/backend/invoice/invoice/edit.html.twig
{% extends 'backend/master.html.twig' %}

{% block title %}Editar fatura: #{{ invoice.number }}{% endblock %}
{% block contentTitle %}Editar fatura: #{{ invoice.number }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Editar fatura: #{{ invoice.number }}</h6>
                </div>
                <div class="card-body">
                    {{ include('backend/invoice/invoice/_form.html.twig', {'button_label': 'Atualizar'}) }}
                    <hr/>
                    <a href="{{ path('backend_invoice_invoice_index') }}"
                       class="btn btn-secondary btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-left"></i>
                        </span>
                        <span class="text">Voltar à lista</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/backend/invoice/invoice/index.html.twig
{% extends 'backend/master.html.twig' %}
{% block title %}Listagem de faturas{% endblock %}
{% block contentTitle %}Listagem de faturas{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Listagem de faturas</h6>
                </div>
                <div class="card-body">
                    {% embed 'backend/component/pagination/header.html.twig' with {pagination: invoices, filters: true} %}{% endembed %}
                    {{ include('backend/invoice/invoice/filters.html.twig') }}


                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>{% embed 'backend/component/pagination/ordered_property.html.twig' with {text: "Número", property: "number"} %}{% endembed %}</th>
                                    <th>{% embed 'backend/component/pagination/ordered_property.html.twig' with {text: "Data", property: "date"} %}{% endembed %}</th>
                                    <th>Emissor</th>
                                    <th>Cliente</th>
                                    <th>Valor</th>
                                    <th>Pago</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for invoice in invoices %}
                                    <tr>
                                        <td>{% embed 'backend/component/identifier/invoice.html.twig'
                                                with {invoice: invoice} %}{% endembed %}</td>
                                        <td>{{ invoice.date|date("d/m/Y") }}</td>
                                        <td>{% embed 'backend/component/identifier/company.html.twig'
                                                with {company: invoice.issuer} %}{% endembed %}</td>
                                        <td>{% embed 'backend/component/identifier/company.html.twig'
                                                with {company: invoice.client} %}{% endembed %}</td>
                                        <td>{{ invoice.total|number_format(2, ".", ".") }}€</td>
                                        <td>{{ invoice.paid  ?
                                            '<span class="badge badge-success">Sim</span>'
                                            : '<span class="badge badge-danger">Não</span>' }}
                                        </td>
                                        <td>
                                            <a href="{{ path('backend_invoice_invoice_edit', {'id': invoice.id}) }}"
                                               class="btn btn-info btn-icon-split">
                                                <span class="icon text-white-50">
                                                  <i class="fas fa-edit"></i>
                                                </span>
                                            </a>
                                            {{ include('backend/invoice/invoice/_delete_form.html.twig') }}
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="5">Não foram encontrados resultados</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Número</th>
                                    <th>Data</th>
                                    <th>Emissor</th>
                                    <th>Cliente</th>
                                    <th>Valor</th>
                                    <th>Pago</th>
                                    <th>Ações</th>
                                </tr>
                            </tfoot>
                        </table>
                        {% embed 'backend/component/pagination/footer.html.twig' with {pagination: invoices} %}{% endembed %}
                    </div>
                </div>

                <div class="card-footer">
                    <a href="{{ path('backend_invoice_invoice_new') }}"
                       class="btn btn-success btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-plus"></i>
                        </span>
                        <span class="text">Criar nova</span>
                    </a>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

templates/backend/invoice/invoice/show.html.twig
{% extends 'backend/master.html.twig' %}

{% block title %}Fatura #{{ invoice.number }} emitida por {{ invoice.issuer.name }} -> {{ invoice.client.name }} {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Fatura #{{ invoice.number }} emitida por
                        {% embed 'backend/component/identifier/company.html.twig' with {company: invoice.issuer} %}{% endembed %} ->
                        {% embed 'backend/component/identifier/company.html.twig' with {company: invoice.client} %}{% endembed %}
                    </h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <p>
                                <strong>Número:</strong>#{{ invoice.number }}<br />
                                <strong>Data:</strong>{{ invoice.date|date("d/m/Y") }}<br />
                                <strong>Emissor:</strong>{% embed 'backend/component/identifier/company.html.twig'
                                    with {company: invoice.issuer} %}{% endembed %}<br />
                                <strong>Cliente:</strong>{% embed 'backend/component/identifier/company.html.twig'
                                    with {company: invoice.client} %}{% endembed %}<br />
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h3>Produtos comprados</h3>

                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Produto</th>
                                        <th>Quantidade</th>
                                        <th>Preço/Unidade</th>
                                        <th>Refúgo</th>
                                        <th>Subtotal</th>
                                        <th class="text-right">Total</th>
                                        <th class="text-right">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in invoice.items %}
                                        <tr>
                                            <td>{% embed 'backend/component/identifier/product.html.twig'
                                                with {product: item.product }%}{% endembed %}</td>
                                            <td>{{ item.quantity }}</td>
                                            <td>{{ item.pricePerUnit|number_format(2, '.', ',') }}€</td>
                                            <td>{{ item.waste }}</td>
                                            <td>{{ item.subTotal|number_format(2, '.', ',') }}€</td>
                                            <td class="text-right">{{ item.total|number_format(2, '.', ',') }}€</td>
                                            <td class="text-right">{{ include('backend/invoice/item/_delete_form.html.twig') }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="5">Subtotal</th>
                                        <th class="text-right">{{ invoice.subTotal|number_format(2, '.', ',') }}€</th>
                                        <th></th>
                                    </tr>
                                    <tr>
                                        <th colspan="5">Total</th>
                                        <th class="text-right">{{ invoice.total|number_format(2, '.', ',') }}€</th>
                                        <th></th>
                                    </tr>

                                </tfoot>
                            </table>
                        </div><!-- col -->


                        <div class="col-12">
                            <h3>Pagamentos</h3>
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Data</th>
                                        <th>Descrição</th>
                                        <th>Método</th>
                                        <th class="text-right">Valor</th>
                                        <th class="text-right">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for payment in invoice.payments %}
                                        <tr>
                                            <td>{{ payment.date|date("d/m/Y") }}</td>
                                            <td>{{ payment.description }}</td>
                                            <td>{{ payment.method }}</td>
                                            <td class="text-right">{{ payment.amount|number_format(2, '.', ',') }}€</td>
                                            <td class="text-right">{{ include('backend/payment/payment/_delete_form.html.twig') }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="3">Total pago:</th>
                                        <th class="text-right">{{ invoice.totalPaid|number_format(2, '.', ',') }}€</th>
                                        <th></th>
                                    </tr>
                                    <tr>
                                        <th colspan="3">Por pagar:</th>
                                        <th class="text-right">{{ invoice.missingToPay|number_format(2, '.', ',') }}€</th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div><!-- col -->
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ path('backend_invoice_invoice_index') }}" class="btn btn-secondary btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-left"></i>
                        </span>
                        <span class="text">Voltar à lista</span>
                    </a>
                    <a href="{{ path('backend_invoice_invoice_edit', {'id': invoice.id}) }}"
                       class="btn btn-info btn-icon-split">
                                                <span class="icon text-white-50">
                                                  <i class="fas fa-edit"></i>
                                                </span>
                        <span class="text">Editar</span>
                    </a>
                    {{ include('backend/invoice/invoice/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}