src/Entity/Employee/WorkDay.php
<?php

namespace App\Entity\Employee;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Employee\WorkDayRepository")
 * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(columns={"employee_id", "day"})})
 * @UniqueEntity(
 *     fields={"employee", "day"},
 *     message="Este dia de trabalho já está registado para este funcionário.",
 *     errorPath="day",
 * )
 */
class WorkDay {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotNull(message="O dia é obrigatório")
     */
    private $day;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Employee\Employee", inversedBy="workDays")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull(message="O funcionário é obrigatório.")
     */
    private $employee;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Employee\WorkInterval", mappedBy="workDay", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"start" = "asc"})
     * @Assert\Count(
     *      min = 1,
     *      minMessage = "Deve adicionar pelo menos um período de trabalho.",
     * )
     * @Assert\Valid()
     */
    private $workIntervals;

    /**
     * @ORM\Column(type="string", length=1048)
     * @Assert\NotNull()
     * @Assert\Length(max="1048", maxMessage="As notas podem ter no máximo {{ limit }} caracteres.")
     */
    private $note;

    public function __construct() {
        $this->setNote("");
        $this->setDay(new \DateTime("now"));
        $this->workIntervals = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getDay(): ?\DateTimeInterface {
        return $this->day;
    }

    public function setDay(\DateTimeInterface $day): self {
        $this->day = $day;

        return $this;
    }

    public function getEmployee(): ?Employee {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self {
        $this->employee = $employee;

        foreach ($this->getWorkIntervals() as $interval) {
            if ($interval->getHourlyWage() === null) {
                $interval->setHourlyWage($employee->getHourlyWage());
            }
        }

        return $this;
    }

    public function getWorkingTime(): \DateTime {
        $time = new \DateTime('00:00');

        foreach ($this->getWorkIntervals() as $workInterval) {
            $time->add($workInterval->getDuration());
        }

        return $time;
    }

    public function getAmountToPay(): float {
        $total = 0.0;

        foreach ($this->getWorkIntervals() as $workInterval) {
            $total += $workInterval->getAmountToPay();
        }

        return $total;
    }

    public function getTotalHoursWorked(): float {
        $total = 0.0;

        foreach ($this->getWorkIntervals() as $workInterval) {
            $total += $workInterval->getHoursWorked();
        }

        return $total;
    }

    /**
     * @return Collection|WorkInterval[]
     */
    public function getWorkIntervals(): Collection {
        return $this->workIntervals;
    }

    public function addWorkInterval(WorkInterval $workInterval): self {
        if (!$this->workIntervals->contains($workInterval)) {
            $this->workIntervals[] = $workInterval;
            $workInterval->setWorkDay($this);
        }

        return $this;
    }

    public function removeWorkInterval(WorkInterval $workInterval): self {
        if ($this->workIntervals->contains($workInterval)) {
            $this->workIntervals->removeElement($workInterval);
            // set the owning side to null (unless already changed)
            if ($workInterval->getWorkDay() === $this) {
                $workInterval->setWorkDay(null);
            }
        }

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): self
    {
        $this->note = $note;

        return $this;
    }
}

src/Form/Employee/EmployeeType.php
<?php

namespace App\Form\Employee;

use App\Entity\Employee\Employee;
use App\Entity\Employee\WorkDay;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeeType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('workingHoursPerDay', NumberType::class, [
                'label' => 'Horas de trabalho obrigatórias',
                'help' => 'Normalmente 8h de trabalho diárias.'
            ])
            ->add('hourlyWage', MoneyType::class, ['label' => 'Salário por hora normal'])
            ->add('extraHourlyWage', MoneyType::class, ['label' => 'Salário por hora extraordinária'])

        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Employee::class,
        ]);
    }
}

src/Form/Employee/WorkDayType.php
<?php

namespace App\Form\Employee;

use App\Entity\Employee\Employee;
use App\Entity\Employee\WorkDay;
use App\Entity\Employee\WorkInterval;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkDayType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /**
         * @var $entity WorkDay
         */
        $entity = $builder->getData();

        $builder->add('employee', EntityType::class, [
                'class' => Employee::class,
                'label' => 'Funcionário',
                'choice_label' => 'name',
            ])
            ->add('day', DateType::class, [
                'label' => 'Dia',
                'widget' => 'single_text',
            ])
            ->add('workIntervals', CollectionType::class, [
                'label' => 'Período de Trabalho',
                'entry_type' => WorkIntervalType::class,
                'entry_options' => [
                    'label' => false
                ],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'delete_empty' => true,
            ])
            ->add("note", TextareaType::class, [
                'label' => 'Notas',
                'help' => 'Este campo é opcional.',
                'required' => false,
                'empty_data' => '',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => WorkDay::class,
        ]);
    }
}

src/Form/Employee/WorkIntervalType.php
<?php

namespace App\Form\Employee;

use App\Entity\Employee\WorkInterval;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkIntervalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('start', DateTimeType::class, [
                'label' => 'Hora de Entrada',
                'widget' => 'single_text',
            ])
            ->add('end', DateTimeType::class, [
                'label' => 'Hora de Saída',
                'widget' => 'single_text',
                'with_seconds' => false,
            ])
            ->add('hourlyWage', MoneyType::class, [
                'label' => 'Vencimento/Hora',
                'required' => false,
                'help' => 'Caso não preencha o sistema cálcula.'

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => WorkInterval::class,
        ]);
    }
}

src/Controller/Backend/Employee/EmployeeController.php
<?php

namespace App\Controller\Backend\Employee;

use App\Controller\Backend\BaseController;
use App\Entity\Employee\Employee;
use App\Form\Employee\EmployeeType;
use App\Repository\Employee\EmployeeRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("backend/employees")
 */
class EmployeeController extends BaseController {
    /**
     * @Route("/", name="backend_employee_employee_index", methods={"GET"})
     */
    public function index(EmployeeRepository $employeeRepository, Request $request): Response {
        $employees = $this->paginateWithSorting($employeeRepository, $request);
        /** @var $invoices Employee[]|PaginatorInterface */

        return $this->render('backend/employee/employee/index.html.twig', [
            'employees' => $employees,
        ]);
    }

    /**
     * @Route("/new", name="backend_employee_employee_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response {
        $employee = new Employee();
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employee);
            $entityManager->flush();

            return $this->redirectToRoute('backend_employee_employee_index');
        }

        return $this->render('backend/employee/employee/new.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_employee_employee_show", methods={"GET"})
     */
    public function show(Employee $employee): Response {
        return $this->render('backend/employee/employee/show.html.twig', [
            'employee' => $employee,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="backend_employee_employee_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Employee $employee): Response {
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('backend_employee_employee_index', [
                'id' => $employee->getId(),
            ]);
        }

        return $this->render('backend/employee/employee/edit.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_employee_employee_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Employee $employee): Response {
        if ($this->isCsrfTokenValid('delete' . $employee->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($employee);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_employee_employee_index');
    }
}

src/Controller/Backend/Employee/WorkDayController.php
<?php

namespace App\Controller\Backend\Employee;

use App\Controller\Backend\BaseController;
use App\Entity\Employee\Employee;
use App\Entity\Employee\WorkDay;
use App\Event\WorkDayCreatedEvent;
use App\Event\WorkDayUpdatedEvent;
use App\Form\Employee\WorkDayType;
use App\Repository\Employee\EmployeeRepository;
use App\Repository\Employee\WorkDayRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("backend/employee/work/day")
 */
class WorkDayController extends BaseController {

    /**
     * @Route("/new", name="backend_employee_work_day_new", methods={"GET","POST"})
     */
    public function new(Request $request, EventDispatcherInterface $eventDispatcher): Response {
        $workDay = new WorkDay();
        $form = $this->createForm(WorkDayType::class, $workDay);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($workDay);
            $eventDispatcher->dispatch( new WorkDayCreatedEvent($workDay));
            $entityManager->flush();

            return $this->redirectToRoute('backend_employee_employee_show', ['id' => $workDay->getEmployee()->getId()]);
        }

        return $this->render('backend/employee/work_day/new.html.twig', [
            'workDay' => $workDay,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="backend_employee_work_day_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, WorkDay $workDay, EventDispatcherInterface $eventDispatcher): Response {
        $form = $this->createForm(WorkDayType::class, $workDay);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventDispatcher->dispatch(new WorkDayUpdatedEvent($workDay));
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('backend_employee_employee_show', [
                'id' => $workDay->getEmployee()->getId(),
            ]);
        }

        return $this->render('backend/employee/work_day/edit.html.twig', [
            'workDay' => $workDay,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show", name="backend_employee_work_day_show", methods={"GET"})
     */
    public function show(Request $request): Response {
        $start = $request->get("start", null);
        $end = $request->get("end", null);

        if ($start !== null && $end !== null) {
            return $this->redirectToRoute("backend_employee_work_day_show_map", [
                'start' => $start,
                'end' => $end
            ]);
        }

        return $this->render('backend/employee/work_day/show.html.twig');
    }

    /**
     * @Route("/show/{start}/{end}", defaults={"start"=null, "end"=null}, name="backend_employee_work_day_show_map", methods={"GET"})
     */
    public function showMap(\DateTime $start, \DateTime $end, EmployeeRepository $employeeRepository): Response {
        $MAX_INTERVAL_DAYS = 90;

        /**
         * @var $employees Employee[]
         */
        $employees = $employeeRepository->findAllWithPaginator('name', 'asc');
        $end->setTime(0, 0, 1); //minor fix to make dateperiod include the end date

        // Checks if the interval is bigger than $MAX_INTERVAL_DAYS days
        if ($end->diff($start)->days > $MAX_INTERVAL_DAYS) {
            $end->setTimestamp($start->getTimestamp() + $MAX_INTERVAL_DAYS * 24 * 60 * 60);
            $this->addFlash("warning", "O periodo máximo de vizualização permitido é de " . $MAX_INTERVAL_DAYS . " dias.");
        }

        // Maps stats
        $hoursPerEmployee = [];
        foreach ($employees as $employee){
            $hoursPerEmployee[$employee->getId()] = [];
            $hours = &$hoursPerEmployee[$employee->getId()];
            $workDays = $employee->getWorkDaysBetween($start, $end);

            foreach ($workDays as $workDay){
                foreach ($workDay->getWorkIntervals() as $workInterval){
                    if(isset($hours[$workInterval->getHourlyWage()])){
                        $hours[$workInterval->getHourlyWage()] += $workInterval->getHoursWorked();
                    }else{
                        $hours[$workInterval->getHourlyWage()] = $workInterval->getHoursWorked();
                    }
                }
            }
        }

        return $this->render('backend/employee/work_day/show_map.html.twig', [
            'hoursPerEmployee' => $hoursPerEmployee,
            'employees' => $employees,
            'startDay' => $start,
            'endDay' => $end,
        ]);
    }

    /**
     * @Route("/{id}", name="backend_employee_work_day_delete", methods={"DELETE"})
     */
    public function delete(Request $request, WorkDay $workDay): Response {
        if ($this->isCsrfTokenValid('delete' . $workDay->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($workDay);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_employee_employee_show', ['id' => $workDay->getEmployee()->getId()]);
    }
}

templates/backend/employee/employee/_delete_form.html.twig
<form method="post" class="d-inline" action="{{ path('backend_employee_employee_delete', {'id': employee.id}) }}"
      onsubmit="return confirm('Tem a certeza que pretende eliminar este funcionário?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
    <button class="btn btn-danger btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-trash"></i>
        </span>
    </button>
</form>

templates/backend/employee/employee/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success btn-icon-split">
        <span class="icon text-white-50">
          <i class="fas fa-check"></i>
        </span>
        <span class="text">{{ button_label|default('Guardar') }}</span>
    </button>
{{ form_end(form) }}

templates/backend/employee/employee/edit.html.twig
{% extends 'backend/master.html.twig' %}

{% block title %}Editar funcionário: {{ employee.name }}{% endblock %}
{% block contentTitle %}Editar funcionário: {{ employee.name }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Editar funcionário: {{ employee.name }}</h6>
                </div>
                <div class="card-body">
                    {{ include('backend/employee/employee/_form.html.twig', {'button_label': 'Atualizar'}) }}
                    <hr/>
                    <a href="{{ path('backend_company_company_index') }}"
                       class="btn btn-secondary btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-left"></i>
                        </span>
                        <span class="text">Voltar à lista</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/backend/employee/employee/index.html.twig
{% extends 'backend/master.html.twig' %}
{% block title %}Funcionários{% endblock %}
{% block contentTitle %}Funcionários{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Funcionários</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        {% embed 'backend/component/pagination/header.html.twig' with {pagination: employees} %}{% endembed %}
                        <table class="table table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th>{% embed 'backend/component/pagination/ordered_property.html.twig' with {text: "Nome", property: "name"} %}{% endembed %}</th>
                                    <th>{% embed 'backend/component/pagination/ordered_property.html.twig' with {text: "Hora Normal", property: "hourlyWage"} %}{% endembed %}</th>
                                    <th>{% embed 'backend/component/pagination/ordered_property.html.twig' with {text: "Hora Extra", property: "extraHourlyWage"} %}{% endembed %}</th>
                                    <th>{% embed 'backend/component/pagination/ordered_property.html.twig' with {text: "Horas por Dia", property: "workingHoursPerDay"} %}{% endembed %}</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for employee in employees %}
                                    <tr>
                                        <td>{% embed 'backend/component/identifier/employee.html.twig'
                                                with {employee: employee} %}{% endembed %}</td>
                                        <td>{{ employee.hourlyWage|number_format(2, ',', '.') }}€</td>
                                        <td>{{ employee.extraHourlyWage|number_format(2, ',', '.') }}€</td>
                                        <td>{{ employee.workingHoursPerDay }}</td>
                                        <td>
                                            <a href="{{ path('backend_employee_employee_edit', {'id': employee.id}) }}"
                                               class="btn btn-info btn-icon-split">
                                                <span class="icon text-white-50">
                                                  <i class="fas fa-edit"></i>
                                                </span>
                                            </a>
                                            {{ include('backend/employee/employee/_delete_form.html.twig') }}
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="5">Não foram encontrados resultados</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>Hora Normal</th>
                                    <th>Hora Extra</th>
                                    <th>Horas por Dia</th>
                                    <th>Acções</th>
                                </tr>
                            </tfoot>
                        </table>
                        {% embed 'backend/component/pagination/footer.html.twig' with {pagination: employees} %}{% endembed %}
                    </div>

                    <a href="{{ path('backend_employee_employee_new') }}"
                       class="btn btn-success btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-plus"></i>
                        </span>
                        <span class="text">Criar novo</span>
                    </a>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

templates/backend/employee/employee/show.html.twig
{% extends 'backend/master.html.twig' %}

{% block title %}Funcionário {{ employee.name }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Funcionário
                        {% embed 'backend/component/identifier/employee.html.twig' with {employee: employee} %}{% endembed %}
                    </h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <p>
                                <strong>Nome: </strong>{{ employee.name }}<br />
                                <strong>Vencimento/Hora: </strong>{{ employee.hourlyWage|number_format(2, ',', '.') }}€<br />
                            </p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <h3>Dias de trabalho</h3>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Dia</th>
                                        <th>Entradas/Saídas</th>
                                        <th>Tempo</th>
                                        <th>Total</th>
                                        <th>Notas</th>
                                        <th>Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for workDay in employee.workDays %}
                                        <tr>
                                            <td>{{ workDay.day|date("d-m-Y") }}</td>
                                            <td>
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th>Entrada</th>
                                                            <th>Saída</th>
                                                            <th>Hora</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for workInterval in workDay.workIntervals %}
                                                            {# @var workInterval \App\Entity\Employee\WorkInterval #}
                                                        <tr>
                                                            <td>{{ workInterval.start|date("H:i") }}h</td>
                                                            <td>
                                                                {% if workInterval.end.format("d-m-Y") != workDay.day.format("d-m-Y") %}
                                                                    {{ workInterval.end|date("d-m-Y") }} às
                                                                {% endif %}
                                                                {{ workInterval.end|date("H:i") }}h
                                                            </td>
                                                            <td>{{ workInterval.hourlyWage|number_format(2, ',', '.') }}€</td>
                                                        </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td>{{ workDay.workingTime|date("H") }}h {{ workDay.workingTime|date("i") }}m</td>
                                            <td>{{ workDay.amountToPay|number_format(2, ',', '.') }}€</td>
                                            <td>{{ workDay.note }}</td>
                                            <td>
                                                <a href="{{ path('backend_employee_work_day_edit', {'id': workDay.id}) }}"
                                                   class="btn btn-info btn-icon-split">
                                                <span class="icon text-white-50">
                                                  <i class="fas fa-edit"></i>
                                                </span>
                                                </a>
                                                {{ include('backend/employee/work_day/_delete_form.html.twig') }}
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="5">Não foram encontrados resultados</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Dia</th>
                                        <th>Entradas/Saídas</th>
                                        <th>Tempo</th>
                                        <th>Total</th>
                                        <th>Notas</th>
                                        <th>Acções</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>


                </div>
                <div class="card-footer">
                    <a href="{{ path('backend_employee_employee_index') }}" class="btn btn-secondary btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-left"></i>
                        </span>
                        <span class="text">Voltar à lista</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}